site_name: EOEPCA Processing Building Block
site_url: https://eoepca.readthedocs.io/projects/processing/en/latest/
repo_url: https://github.com/EOEPCA/document-processing/
edit_uri: "edit/main/docs/"

nav:
  - EOEPCA Documentation: https://eoepca.readthedocs.io/
  - Processing Building Block:
    - index.md
    
    - Design:
      - design/overview.md
      - Processing engines:
        - OGC Application Packages via OGC API Processes: 
          - Design: design/processing-engine/oa.md
          - Processing Runners:
            - Kubernetes: design/processing-runner/kubernetes.md
            - Docker: design/processing-runner/docker.md
            - High-Performance Computing: design/processing-runner/hpc.md
            - Argo Workflows: design/processing-runner/argo.md
            - Dask Distributed: design/processing-runner/dask.md
          - Usage:
            - oa/usage/tutorials.md
            - oa/usage/howtos.md
          - Administration:
            - oa/admin/configuration.md
            - oa/admin/maintenance.md
          - API:
            - oa/api/endpoint-specification.md
            - oa/api/usage.md
          - Getting Started:
            - oa/getting-started/quick-start.md
        - openEO Process Graphs via the openEO Specification: 
          - Design: design/processing-engine/openeo.md
          - Usage:
            - openeo/usage/tutorials.md
            - openeo/usage/howtos.md
          - Administration:
            - openeo/admin/configuration.md
            - openeo/admin/maintenance.md
          - API:
            - openeo/api/endpoint-specification.md
            - openeo/api/usage.md
          - Getting Started:
            - openeo/getting-started/quick-start.md

theme:
  # name: mkdocs
  # name: readthedocs
  name: material # https://squidfunk.github.io/mkdocs-material/creating-your-site/
  navigation_depth: 4

  # For `material` theme...
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    # Navigation
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    # - toc.integrate
    - navigation.top
    # Content
    - content.code.copy
    - content.action.edit
    # Search
    - search.highlight
    - search.share
    - search.suggest

extra_css:
  - css/eoepca.css

plugins:
  - autorefs
  - search
  - swagger-ui-tag
  - mermaid2:
      version: 10.6.0
  # - pub-debugger:
  #     console_log:
  #       enabled: true
  #       log_level: INFO
  #     file_log:
  #       enabled: false
  #     zip_log:
  #       enabled: false

markdown_extensions:
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 4
  - smarty
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
          
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
